# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aibris < Formula
  desc "Clean filesystem leftovers from AI coding agents"
  homepage "https://github.com/sungjunlee/aibris"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.0/aibris_darwin_amd64.tar.gz"
      sha256 "61e98f77e306851d44daf9c85758b8475ba133026bc049557f6d28b6364b58ca"

      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.0/aibris_darwin_arm64.tar.gz"
      sha256 "f1dd03defbdac380726c59ba73a58a2470e2c0fb6197684a8ad34d670778fc35"

      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.0/aibris_linux_amd64.tar.gz"
      sha256 "a1b2f83fa2184fd0687ef533fce1717f7bde4bf3d9c74cec7911aee600497785"
      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.0/aibris_linux_arm64.tar.gz"
      sha256 "3cb854324739c34eb98e7fc99e4dea203bd8f407b73f097075c58b4616c3b016"
      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
  end

  test do
    assert_match "aibris version 0.12.0", shell_output("#{bin}/aibris --version")
  end
end
