# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aibris < Formula
  desc "Clean filesystem leftovers from AI coding agents"
  homepage "https://github.com/sungjunlee/aibris"
  version "0.12.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.1/aibris_darwin_amd64.tar.gz"
      sha256 "69c04434ea7c919e0829281e7e09cf8331cf535e87638ab6c2c4dce8662c671d"

      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.1/aibris_darwin_arm64.tar.gz"
      sha256 "df6edfaf535bf2368b5144d9288b03e63ca2ecf7b8772be4797e8822635dd2d0"

      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.1/aibris_linux_amd64.tar.gz"
      sha256 "02c095dc40d5405be10bf27ef4dea9fb672e44daf81815ae7e85eb54afd14fa4"
      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sungjunlee/aibris/releases/download/v0.12.1/aibris_linux_arm64.tar.gz"
      sha256 "3df80d19422b6e36687e90f4bd9410221f3de8fa34f26deac03d7ff1f7cfad3f"
      define_method(:install) do
        bin.install "aibris"
        generate_completions_from_executable(bin/"aibris", "completion")
        man1.install Dir["release-assets/man/*.1"]
      end
    end
  end

  test do
    assert_match "aibris version 0.12.1", shell_output("#{bin}/aibris --version")
  end
end
